/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * # Safety
 * This is unsafe, it calls libc functions
 */
export function initFaultHandler(): void
/**
 * # Safety
 * This is unsafe, it calls libc functions
 */
export function triggerSignal(): void
